# Generated by Django 4.2.1 on 2023-05-27 15:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_6', models.ImageField(blank=True, null=True, upload_to='')),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('return_validity', models.IntegerField(default=7)),
                ('exchange_validity', models.IntegerField(default=7)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_items', to='WmVoice.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('txn_id', models.CharField(max_length=50)),
                ('placed_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(blank=True, max_length=12, null=True)),
                ('password', models.CharField(max_length=256)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('birthday', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_reviews', to='WmVoice.item')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choice_reviews', to='WmVoice.user')),
            ],
        ),
        migrations.CreateModel(
            name='ItemVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_visit', models.DateTimeField(default=django.utils.timezone.now)),
                ('visit_count', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_visits', to='WmVoice.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_visits', to='WmVoice.user')),
            ],
        ),
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivered_on', models.DateTimeField(blank=True, null=True)),
                ('return_valid_till', models.DateTimeField(blank=True, null=True)),
                ('exchange_valid_till', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_orders', to='WmVoice.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_ordered_items', to='WmVoice.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_ordered_items', to='WmVoice.user')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_cart_items', to='WmVoice.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_cart_items', to='WmVoice.user')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='choice_items', to='WmVoice.tag'),
        ),
    ]
