# Generated by Django 4.2.1 on 2023-06-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WmVoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorder',
            name='return_status',
            field=models.CharField(blank=True, choices=[('Return Initiated', 'Return Initiated'), ('Item Picked Up', 'Item Picked Up')], max_length=20, null=True),
        ),
    ]
